# Generated by Django 4.2 on 2024-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactapplication',
            name='is_cantacted',
            field=models.BooleanField(default=False),
        ),
    ]
