# Generated by Django 4.2 on 2024-07-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercontactapplication_is_cantacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontactapplication',
            old_name='is_cantacted',
            new_name='is_contacted',
        ),
    ]
