# Generated by Django 4.2 on 2024-06-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usercontactapplication',
            table='user_contact_application',
        ),
    ]
