# Generated by Django 4.2 on 2024-07-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usercontactapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontactapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Contact Application', 'verbose_name_plural': 'User Contact Applications'},
        ),
    ]
