# Generated by Django 4.2 on 2024-06-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_lang_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
