# Generated by Django 4.2 on 2024-06-25 07:57

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserCreateManager()),
            ],
        ),
    ]
