# Generated by Django 4.2 on 2024-06-27 06:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to='photos/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'db_table': 'gallery_photo',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_telegram', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('location_text', models.TextField(verbose_name='location_text')),
                ('location_text_ru', models.TextField(null=True, verbose_name='location_text')),
                ('location_text_uz', models.TextField(null=True, verbose_name='location_text')),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('telegram_bot', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
    ]
