# Generated by Django 4.2 on 2024-06-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='pages',
        ),
        migrations.AlterModelTable(
            name='settings',
            table='settings',
        ),
    ]
