# Generated by Django 4.2 on 2024-06-27 06:31

from django.db import migrations
from common.models import Settings


def create_settings(*args, **kwargs):
    Settings.objects.create(
        contact_telegram='chere_uz',
        longitude=120,
        latitude=37,
        location_text='text',
        working_hours_start="00:00:00",
        working_hours_end="00:00:00",
        telegram_bot='chere_bot'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
