# Generated by Django 4.2 on 2024-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_settings_working_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='working_hours_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='working_hours_start',
            field=models.TimeField(),
        ),
    ]
