# Generated by Django 4.2 on 2024-06-25 08:06

from django.db import migrations

from common.models import Settings


def create_default_settings(*args, **kwargs):
    print(*args, **kwargs)
    Settings.objects.create(
        contact_telegram="chere.uz",
        longitude = 0,
        latitude = 0,
        location_text = 'text',
        working_hours_start = "00:00:00",
        working_hours_end = "23:00:00",
        telegram_bot = 'chere_telegram_bot',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_settings_contact_phone'),
    ]
    atomic = False
    operations = [
        migrations.RunPython(create_default_settings)
    ]
