# Generated by Django 4.2 on 2024-06-25 12:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20240625_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_text',
            field=models.TextField(verbose_name='location_text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_text_ru',
            field=models.TextField(null=True, verbose_name='location_text'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_text_uz',
            field=models.TextField(null=True, verbose_name='location_text'),
        ),
    ]
