# Generated by Django 4.2 on 2024-06-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_products', to='products.product'),
        ),
        migrations.AlterModelTable(
            name='freeproduct',
            table='free_products',
        ),
        migrations.AlterModelTable(
            name='galleryphoto',
            table='gallery_photo',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
