# Generated by Django 4.2 on 2024-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_freeproduct_product_alter_freeproduct_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/'),
        ),
    ]
